#!/usr/bin/env bash

declare jq_filter='

    capture( "(?<outer>.*) bags contain (?<inner>no other bags[.]|(.*)[.])"; "g")
    | { 
        outer, 
        inner : 
          ( .inner 
          | if . == "no other bags." 
              then { amount : 0, name : "" }
              else splits( "," ) | capture( "(?<amount>\\d+) (?<name>.*) bag[s]?" )
            end
          )
      }
    | [ .outer, ( .inner.amount | tonumber ), .inner.name ]
    | @csv

'

echo 'outer,amount,inner'

# This was the sample for part 1
# jq --raw-input --raw-output --slurp "$jq_filter" <<EOF
# light red bags contain 1 bright white bag, 2 muted yellow bags.
# dark orange bags contain 3 bright white bags, 4 muted yellow bags.
# bright white bags contain 1 shiny gold bag.
# muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.
# shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.
# dark olive bags contain 3 faded blue bags, 4 dotted black bags.
# vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.
# faded blue bags contain no other bags.
# dotted black bags contain no other bags.
# EOF

# sample of part 2
jq --raw-input --raw-output --slurp "$jq_filter" <<EOF
shiny gold bags contain 2 dark red bags.
dark red bags contain 2 dark orange bags.
dark orange bags contain 2 dark yellow bags.
dark yellow bags contain 2 dark green bags.
dark green bags contain 2 dark blue bags.
dark blue bags contain 2 dark violet bags.
dark violet bags contain no other bags.
EOF