#!/usr/bin/env bash

declare jq_filter='
    split( "\n\n" ) 
    | 
      ( .[ ] 
      | split( "[\\s\\n]"; "" ) 
      | map( select( "" != . ) )
      | map( split( ":" ) ) 
      | map({ key : .[ 0 ], value : .[ 1 ] }) 
      | from_entries
      )
    |
      ( . as { $byr, $iyr, $eyr, $hgt, $hcl, $ecl, $pid, $cid }
      | [ $byr, $iyr, $eyr, $hgt, $hcl, $ecl, $pid, $cid, ( . | tojson ) ]
      )
    | @csv
'

echo 'byr,iyr,eyr,hgt,hcl,ecl,pid,cid,passport'

jq --raw-input --raw-output --slurp "$jq_filter" <<EOF
ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in
EOF